apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    provider: azure
    cloud: azure
  name: xclusters.azure.platform.haarchri.io
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: platform.haarchri.io/v1alpha1
    kind: XCluster
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: crossplane-contrib-function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: resource-group
            base:
              apiVersion: azure.upbound.io/v1beta1
              kind: ResourceGroup
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: spec.forProvider.location
              - type: FromCompositeFieldPath
                fromFieldPath: status.cluster.azure.tenantId
                toFieldPath: metadata.annotations[crossplane.io/external-name]
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.parameters.region
              #   toFieldPath: spec.forProvider.location[0].region

          - name: secret-input
            base:
              apiVersion: kubernetes.crossplane.io/v1alpha1
              kind: Object
              metadata:
                annotations:
                  crossplane.io/external-name: azure-creds
              spec:
                managementPolicy: Observe
                forProvider:
                  manifest:
                    apiVersion: v1
                    kind: Secret
                    metadata:
                      namespace: upbound-system
                      name: azure-creds
            patches:
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.manifest.data.credentials
                toFieldPath: status.cluster.azure.tenantId
                transforms:
                  - type: string
                    string:
                      type: Convert
                      convert: FromBase64
                  - type: string
                    string:
                      type: Regexp
                      regexp:
                        match: '"tenantId":\s*"([^"]+)"'
                        group: 1
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.manifest.data.credentials
                toFieldPath: status.cluster.azure.subscriptionId
                transforms:
                  - type: string
                    string:
                      type: Convert
                      convert: FromBase64
                  - type: string
                    string:
                      type: Regexp
                      regexp:
                        match: '"subscriptionId":\s*"([^"]+)"'
                        group: 1
