apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclusters.platform.haarchri.io
spec:
  defaultCompositeDeletePolicy: Foreground
  connectionSecretKeys:
  - kubeconfig
  group: platform.haarchri.io
  names:
    kind: XCluster
    plural: xclusters
  claimNames:
    kind: Cluster
    plural: clusters
  defaultCompositionRef:
    name: xclusters.azure.platform.haarchri.io
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                description: AKS configuration parameters.
                properties:
                  region:
                    type: string
                    description: Region is the region you'd like your resource to be created in.
                  deletionPolicy:
                    description: Delete the external resources when the Claim/XR is deleted. Defaults to Delete
                    enum:
                    - Delete
                    - Orphan
                    type: string
                    default: Delete
                  providerConfigName:
                    description: Crossplane ProviderConfig to use for provisioning this resources
                    type: string
                    default: default
                required:
                - region
                - deletionPolicy
                - providerConfigName
            required:
            - parameters
          status:
            description: A Status represents the observed state
            properties:
              cluster:
                description: Freeform field containing status information for aks
                type: object
                x-kubernetes-preserve-unknown-fields: true
            type: object
